package com.baran3575.vergconnector;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import java.util.stream.Stream;
import cpw.mods.jarhandling.JarContents;
import net.neoforged.neoforgespi.ILaunchContext;
import net.neoforged.neoforgespi.locating.IDiscoveryPipeline;
import net.neoforged.neoforgespi.locating.IModFileCandidateLocator;
import net.neoforged.neoforgespi.locating.ModFileDiscoveryAttributes;
import net.neoforged.neoforgespi.locating.IncompatibleFileReporting;
import net.neoforged.fml.loading.FMLPaths;

public class VergConnectorLocator implements IModFileCandidateLocator {

    @Override
    public void findCandidates(ILaunchContext context, IDiscoveryPipeline pipeline) {
        System.out.println("[Verg Connector] Scanning mods directory for Fabric and Forge mods...");

        // Dirty reflection hack to remove "is a Fabric mod" warnings generated by ModsFolderLocator
        try {
            for (java.lang.reflect.Field f : pipeline.getClass().getDeclaredFields()) {
                if (java.util.List.class.isAssignableFrom(f.getType())) {
                    f.setAccessible(true);
                    java.util.List<?> issues = (java.util.List<?>) f.get(pipeline);
                    if (issues != null) {
                        issues.removeIf(issue -> issue != null && issue.toString().contains("is a Fabric mod"));
                    }
                }
            }
        } catch (Exception e) {
            System.err.println("[Verg Connector] Failed to suppress Fabric mod warnings: " + e.getMessage());
        }

        Path modsDir = FMLPaths.MODSDIR.get();
        if (!Files.exists(modsDir)) {
            return;
        }

        try (Stream<Path> stream = Files.list(modsDir)) {
            stream.filter(path -> path.toString().endsWith(".jar"))
                  .forEach(path -> {
                      try {
                          processJar(path, pipeline);
                      } catch (Exception e) {
                          System.err.println("[Verg Connector] Failed to process jar: " + path + ". Error: " + e.getMessage());
                      }
                  });
        } catch (IOException e) {
            System.err.println("[Verg Connector] Failed to list mods directory: " + e.getMessage());
        }
    }

    private void processJar(Path path, IDiscoveryPipeline pipeline) throws Exception {
        boolean isFabric = false;
        try (java.util.zip.ZipFile zip = new java.util.zip.ZipFile(path.toFile())) {
            if (zip.getEntry("fabric.mod.json") != null) {
                isFabric = true;
            }
        }
        
        Path finalPath = path;
        if (isFabric) {
            System.out.println("[Verg Connector] Found Fabric mod: " + path.getFileName());
            try {
                Path mappings = com.baran3575.vergconnector.remapper.MappingManager.getMappingsFile();
                Path cacheDir = FMLPaths.GAMEDIR.get().resolve(".vergconnector").resolve("remapped");
                if (!Files.exists(cacheDir)) Files.createDirectories(cacheDir);
                
                Path remappedPath = cacheDir.resolve(path.getFileName().toString());
                boolean needsRemap = !Files.exists(remappedPath);
                
                String currentVer = "v8"; // Invalidate cache when remapping logic updates
                Path verFile = cacheDir.resolve(".remapper_version");
                
                if (!needsRemap) {
                    long origTime = Files.getLastModifiedTime(path).toMillis();
                    long remapTime = Files.getLastModifiedTime(remappedPath).toMillis();
                    if (origTime > remapTime) {
                        System.out.println("[Verg Connector] Original mod " + path.getFileName() + " has changed. Re-remapping...");
                        Files.deleteIfExists(remappedPath);
                        needsRemap = true;
                    }
                }
                
                boolean versionMatch = false;
                if (Files.exists(verFile)) {
                    try {
                        String savedVer = Files.readString(verFile).trim();
                        if (currentVer.equals(savedVer)) {
                            versionMatch = true;
                        }
                    } catch (IOException e) {}
                }
                
                if (!versionMatch) {
                    System.out.println("[Verg Connector] Remapper version changed or missing. Invalidating cache...");
                    try (Stream<Path> s = Files.list(cacheDir)) {
                        s.filter(p -> !p.getFileName().toString().equals(".remapper_version")).forEach(p -> {
                            try {
                                if (!Files.isDirectory(p)) {
                                    Files.deleteIfExists(p);
                                }
                            } catch (IOException e) {}
                        });
                    } catch (IOException e) {}
                    try {
                        Files.writeString(verFile, currentVer);
                    } catch (IOException e) {}
                    needsRemap = true;
                }
                
                if (needsRemap) {
                    com.baran3575.vergconnector.remapper.JarRemapper.remapJar(path, remappedPath, mappings);
                }
                finalPath = remappedPath;
            } catch (Exception e) {
                System.err.println("[Verg Connector] Failed to remap Fabric mod " + path.getFileName() + ": " + e.getMessage());
                // Fallback to unremapped
            }
            
            cpw.mods.jarhandling.JarContents contents = com.baran3575.vergconnector.jarhandling.FabricJarContentsWrapper.createJarContents(finalPath);
            if (contents != null) {
                pipeline.addJarContent(contents, ModFileDiscoveryAttributes.DEFAULT.withLocator(this), IncompatibleFileReporting.IGNORE);
            }
        }
    }
}
